# Generated by Django 6.0 on 2026-01-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
