# Generated by Django 6.0 on 2026-01-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmatching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
