# Generated by Django 6.0 on 2026-01-10 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmatching', '0003_resume_delete_job_delete_onlinejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='text',
            new_name='resume_text',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='file',
        ),
        migrations.AddField(
            model_name='resume',
            name='candidate_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobmatching.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobmatching.resume')),
            ],
        ),
    ]
