# Generated by Django 6.0 on 2026-01-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmatching', '0004_job_rename_text_resume_resume_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(default='Careerjet', max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='similarity_score',
            field=models.FloatField(default=0),
        ),
    ]
