# Generated by Django 6.0 on 2026-01-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmatching', '0006_remove_job_company_remove_resume_resume_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.CharField(default='Manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(help_text='Comma-separated skills'),
        ),
    ]
