# Generated by Django 6.0 on 2026-01-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmatching', '0007_job_company_alter_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='applied_jobs',
            field=models.ManyToManyField(blank=True, related_name='applicants', to='jobmatching.job'),
        ),
    ]
