# Generated by Django 6.0 on 2026-01-12 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmatching', '0008_resume_applied_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='applied_jobs',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_file',
        ),
        migrations.AlterField(
            model_name='resume',
            name='candidate_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(help_text='Comma separated skills'),
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('apply_url', models.URLField()),
                ('matched_skills', models.TextField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobmatching.resume')),
            ],
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
