# Generated by Django 6.0 on 2026-01-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobmatching', '0009_remove_resume_applied_jobs_remove_resume_resume_file_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppliedJob',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
