# Generated by Django 6.0 on 2026-01-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmatching', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchedjob',
            name='is_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='matchedjob',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='matchedjob',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='matchedjob',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
